DEBUG = True
TEMPLATE_DEBUG = DEBUG
DEV_ENV = True

EXISTDB_SERVER_PROTOCOL = "http://"
EXISTDB_SERVER_HOST     = "kamina.library.emory.edu:8080/exist/"
EXISTDB_SERVER_USER     = "bbolte"
EXISTDB_SERVER_PASSWORD = "!QAZ@WSX"
EXISTDB_SERVER_URL      = EXISTDB_SERVER_PROTOCOL + EXISTDB_SERVER_HOST
EXISTDB_ROOT_COLLECTION = "/merton"
#EXISTDB_TEST_COLLECTION = ""

from dateutil import tz
EXISTDB_SERVER_TIMEZONE = tz.tzlocal()
